version: '3.8'

services:
  aged_gender_inference:
    build:
      context: .
      dockerfile: Dockerfile.jetson
    image: aged_gender_jetson
    runtime: nvidia
    network_mode: "host"
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: /bin/bash
    tty: true
    stdin_open: true
